#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
picom &

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
